---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: rancher/dapper:v0.6.0
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: stage-binaries
  pull: default
  image: rancher/dapper:v0.6.0
  commands:
  - "cp -r ./bin/* ./package/"
  when:
    instance:
    - drone-publish.rancher.io
    refs:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: publish-image
  pull: default
  image: plugins/docker
  settings:
    context: package/
    dockerfile: package/Dockerfile
    repo: rancher/kube-api-auth
    tag: "${DRONE_TAG}-amd64"
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    refs:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  pull: default
  image: rancher/dapper:v0.6.0
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: stage-binaries
  pull: default
  image: rancher/dapper:v0.6.0
  commands:
  - "cp -r ./bin/* ./package/"
  when:
    instance:
    - drone-publish.rancher.io
    refs:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: publish-image
  pull: default
  image: plugins/docker
  settings:
    context: package/
    dockerfile: package/Dockerfile
    repo: rancher/kube-api-auth
    tag: "${DRONE_TAG}-arm64"
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    refs:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: manifest

steps:
- name: push-master-manifest
  image: plugins/manifest:1.0.2
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: "rancher/kube-api-auth:${DRONE_TAG}"
    template: "rancher/kube-api-auth:${DRONE_TAG}-ARCH"
    platforms:
    - linux/amd64
    - linux/arm64
  when:
    instance:
    - drone-publish.rancher.io
    event:
    - tag
depends_on:
- amd64
- arm64
