#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../image
./build

cp ../bin/kube-api-auth-full ../bin/kube-api-auth
echo -n "_sqmagic_" >> ../bin/kube-api-auth
cat main.squashfs >> ../bin/kube-api-auth
