#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running validation

echo Tidying up modules
go mod tidy

echo Verifying modules
go mod verify

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
  echo "Encountered dirty repo!"
  exit 1
fi

PACKAGES="$(go list ./...)"
echo Running: go fmt
test -z "$(go fmt ${PACKAGES} | tee /dev/stderr)"

if ! command -v golangci-lint; then
    echo "Skipping validation on ARCHs other than linux amd64"
    exit
fi

echo Running: golangci-lint
golangci-lint run --timeout=3m
