#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running validation

echo Tidying up modules
go mod tidy

echo Verifying modules
go mod verify

echo Regenerating code
go generate ./...

echo Formatting
go fmt ./...

dirty_files="$(git status --porcelain --untracked-files=no)"
if [ -n "$dirty_files" ]; then
  echo "Encountered dirty repo! Aborting."
  echo "One of 'go mod tidy', 'go generate ./...', or 'go fmt ./...' produced changes."
  echo "Run 'make validate' locally, commit the resulting diff, and re-push."
  echo "Files with pending changes:"
  echo "$dirty_files"
  exit 1
fi

if ! command -v golangci-lint; then
  echo "Skipping golangci-lint (not installed)"
  exit
fi

echo Running: golangci-lint
golangci-lint run -v
