name: CI Build and Check

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GOLANG_CI_LINT_VERSION: v2.7.2
  IMAGE: rancher/kube-api-auth

permissions:
  contents: read

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Get Sources
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
      with:
        go-version-file: 'go.mod'
        cache: false

    # https://github.com/golang/go/issues/75031
    - name: Set toolchain version
      run: go env -w GOTOOLCHAIN=go1.25.4+auto

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
      with:
        version: ${{ env.GOLANG_CI_LINT_VERSION }}
        install-only: true

    - name: Validate the sources
      run: |
        ./scripts/validate

    - name: Test
      run: ./scripts/test

  build:
    runs-on: ubuntu-latest
    needs:
      - linter
    strategy:
      fail-fast: false
      matrix:
        os:
          - linux
        arch:
          - amd64
          - arm64
    steps:
    - name: Prepare Matrix Instance
      id: prepare
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: |
        echo "GOOS=$GOOS"
        echo "GOOS=$GOOS"     >> "$GITHUB_OUTPUT"
        echo "GOARCH=$GOARCH"
        echo "GOARCH=$GOARCH" >> "$GITHUB_OUTPUT"
        echo "ARCH=$GOARCH"
        echo "ARCH=$GOARCH"   >> "$GITHUB_OUTPUT"

    - name: Get Sources
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      with:
        persist-credentials: false

    - name: Determine Tag
      id: get-TAG
      run: |
        TAG=$(git describe --always)
        echo "TAG=$TAG"
        echo "TAG=$TAG" >> "$GITHUB_OUTPUT"

    - name: Set up Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
      with:
        go-version-file: 'go.mod'
        cache: false

    - name: Build
      env:
        GOOS: ${{ steps.prepare.outputs.GOOS }}
        GOARCH: ${{ steps.prepare.outputs.GOARCH }}
      run: |
        ./scripts/build
        echo Stage binary for packaging step
        cp -rv ./bin/* ./package/

    - name: Package up into container image
      uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
      with:
        context: package
        push: false
        tags: ${{ env.IMAGE }}:${{ steps.get-TAG.outputs.TAG }}-${{ steps.prepare.outputs.ARCH }}
        file: package/Dockerfile
